[tool.poetry]
name = "rasb_pi_timelapse"
version = "0.0.1"
description = ""
authors = ["Parametricall <22248105+Parametricall@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^7.2.0"
requests = "^2.24.0"
# opencv-contrib-python = "^4.4.0"
#python-vlc = "^3.0.11115"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
